### ISSUE TITLE
graceful recovery when ProtoBuf is missing

### ISSUE THREAD

**Issue by skal65535** [googleinterns/step255-2020#4]
This is more a remark than an 'issue':

It's good practice to disable targets that can't be built if a packet/library is missing.
Sometimes it can't be done because the dependency is absolutely required. In this case an error message is useful.

Anyways, here's what i get on my system *without* protobuf installed, just FYI. No action needed.

> cmake ../
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "62") 
-- Found ZLIB: /usr/local/lib/libz.dylib (found version "1.2.11") 
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.34") 
-- Found TIFF: /usr/local/lib/libtiff.dylib (found version "4.0.9") 
-- Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) 
-- Configuring done
CMake Error at CMakeLists.txt:46 (add_executable):
  Target "thumbnailer" links to target "protobuf::libprotobuf" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:42 (add_library):
  Target "thumbnailer_lib" links to target "protobuf::libprotobuf" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by vrabaud** [comment]
The targets linking to protobuf (thumbnailer for now) should only be built if protobuf was found.
Documentation that you need is here:
https://cmake.org/cmake/help/latest/command/if.html
https://cmake.org/cmake/help/v3.9/module/FindProtobuf.html
Assigning the bug.
